language: python
python:
  - "2.7"
# command to install dependencies
#before_install:
#  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
#  - sudo apt-get update -q
#  - sudo apt-get install gcc-4.8 -y
# command to run tests
script:
  - python pytest # or py.test for Python versions 3.5 and below
  - python pytest
