#!/bin/sh
projects=(Math) # array of projects to test
numbugs=$1  # pass in the number of bugs to test
commitminpath=$(pwd)
defects4jpath="$(which defects4j)"
defects4jpath=${defects4jpath::-13}  # cut off the bin/defects4j

for project in ${projects[@]}; do
  projectpath=${defects4jpath}projects/$project/
  bugs=($(head -$numbugs "$projectpath"commit-db))  # array of the top numbugs bugs
  for bug in ${bugs[@]}; do
    # split up the bug line into it's componenets
    bugsplit=($(echo "$bug" | tr ',' '\n'))
    bugnum=${bugsplit[0]}
    buggyid=${bugsplit[1]}
    fixedid=${bugsplit[2]}

    # get the path to the source files for this project
    srctestpath=($(grep "$fixedid" "$projectpath"dir_map.csv | tr ',' '\n'))
    srcpath=${srctestpath[1]}

    # checkout the repo for the bugnum
    repo=/tmp/$project-$bugnum
    rm -rf $repo
    defects4j checkout -p $project -v "$bugnum"f -w $repo
    cd $repo

    # create all the diffs
    echo "$repo" > /tmp/fullDiff.txt
    echo "$repo" > /tmp/diffWithContext.txt

    # get the diff and split into one file per hunk
    git diff $buggyid $fixedid -- $srcpath >> /tmp/fullDiff.txt
    mkdir -p /tmp/cmpatches
    rm -rf /tmp/cmpatches/*
    ${commitminpath}/splitpatch.rb -H /tmp/fullDiff.txt
    mv *.patch /tmp/cmpatches

    git diff $buggyid $fixedid -- $srcpath >> /tmp/diffWithContext.txt
    git diff $buggyid $fixedid --name-only -- $srcpath > /tmp/files.txt

    # run our tool. Normally you pass in a testname, but we don't need it here
    python ${commitminpath}/rundelta.py testname defects4j.test $buggyid
    python ${commitminpath}/diffMaker.py
    mv /tmp/diff1.txt ${commitminpath}/experiments/
    mv /tmp/diff2.txt ${commitminpath}/experiments/
    python dataProcessor.py

    # clean up
    #rm /tmp/fullDiff.txt /tmp/diffWithContext.txt /tmp/files.txt
    #rm -rf $repo
  done
done


